name: flake8 Lint

on:
  push:
    branches:
      - main
      - test 
  pull_request:
    branches:
      - main
      - test      
jobs:
  flake8-lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - name: Check out source repository
        uses: actions/checkout@v3
      - name: Set up Python environment
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Super Lint
        uses: super-linter/super-linter@v6.3.0
        with:
          exclude: "scripts/*"
